---
jobs:
  build:
    environment:
      - CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing dependencies
          command: |
            set -x
            apk add --no-cache --no-progress bash musl-dev python3-dev libressl-dev libffi-dev gcc py3-pip make && pip3 install --upgrade pip && pip3 install docker-compose
            
      - run:
          name: Logging Docker and Application information
          command: |
            set -x
            docker -v
            docker-compose -v
            ls -l
      - run:
          name: Testing the Docker installation
          command: docker container run hello-world