---
jobs:
  build:
    environment:
      - CRYPTOGRAPHY_DONT_BUILD_RUST: 1
      - COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing dependencies
          command: |
            set -x
            apk add --no-cache --no-progress bash musl-dev python3-dev libressl-dev libffi-dev gcc py3-pip make && pip3 install --upgrade pip && pip3 install wheel docker-compose            
      - run:
          name: Preparing the environment
          command: ./scripts/setup-env.sh
      - run:
          name: Running the test suite
          command: sh ./scripts/run-specs.sh