---
jobs:
  build:
    environment:
      - CRYPTOGRAPHY_DONT_BUILD_RUST: 1
      - COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
  
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Installing dependencies
          command: |
            set -x
            apk add --no-cache --no-progress bash musl-dev python3-dev libressl-dev libffi-dev gcc py3-pip make && pip3 install --upgrade pip && pip3 install wheel docker-compose            
      - run:
          name: Preparing the environment
          command: sh ./scripts/setup-env.sh
      - run:
          name: Running the test suite
          command: sh ./scripts/run-specs.sh
      - run:
          name: Signing in to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Building and pushing images
          command: |
            set -e
            export COMPOSE_FILE=docker-compose.build.yml
            export GIT_SHA=`git rev-parse HEAD`
            docker-compose build --pull
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose push
      - store_artifacts:
          path: /tmp/artifacts